import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { Roboto } from '@next/font/google'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={styles.nav}>
          <div className={styles.nav_container}>
            <h1>Home</h1>
          </div>
        </div>
      </header>
      <main className={roboto.className}>
        <div className={styles.main_section}>
          <div className={styles.container}>
            <div className={styles.side_box}>
              <h1 className={styles.name}>Marcel Freiberg</h1>
              <p className={styles.paragraph}>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident, ea. Quasi quaerat recusandae culpa ratione rerum eligendi provident voluptas incidunt voluptate molestias, soluta</p>
            </div>
            <div className={styles.side_image}>
              <Image
                className={styles.side_image_m}
                src="/SKP_0981.png"
                alt="Marcel Freiberg"
                fill
                priority
              />
            </div>
          </div>
        </div>
        <div className={styles.section}>
          <div className={styles.container}>
            <div className={styles.side_box}>
              <h1 className={styles.name}>Marcel Freiberg</h1>
              <p className={styles.paragraph}>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident, ea. Quasi quaerat recusandae culpa ratione rerum eligendi provident voluptas incidunt voluptate molestias, soluta</p>
            </div>
            <div className={styles.side_box}>
              <h1 className={styles.name}>Marcel Freiberg</h1>
              <p className={styles.paragraph}>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident, ea. Quasi quaerat recusandae culpa ratione rerum eligendi provident voluptas incidunt voluptate molestias, soluta</p>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
